<?php
$this->layout('minimal', [
    'title' => 'Set Up',
    'page_class' => 'login-content'
]);

/** @var \Azura\Assets $assets */
$assets->load('zxcvbn');
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title mb-0">
                <b>Dein</b>Streamserver Setup
            </h2>

            <p class="text-left"><small>Powered by <a href="https://azuracast.com/" target="_blank">AzuraCast</a></small></p>
            <p class="text-left">Willkommen bei deinem dedicated Streamingserver von <b>Dein</b>Streamingserver!</p>
            <p class="text-left">Mit den folgenden Schritten startest du deinen Streamserver, bitte fülle alle Felder aus.</p>

            <form id="login-form" class="pr-5" action="" method="post">
                <div class="input-group">
                    <div class="floating-label">
                        <label for="username"><?=__('E-mail Address') ?></label>
                        <input type="email" name="username" class="form-control" placeholder="" required>
                    </div>
                    <span class="input-group-icon">
                        <i class="material-icons">email</i>
                    </span>
                </div>

                <div class="input-group mt-2">
                    <div class="floating-label">
                        <label for="password"><?=__('Password') ?></label>
                        <input type="password" name="password" class="form-control" placeholder="" required>
                    </div>

                    <span class="input-group-icon">
                        <i class="material-icons">vpn_key</i>
                    </span>
                </div>

                <button type="submit" role="button" title="<?=__('Create Account') ?>" class="btn btn-login btn-primary btn-float">
                    <i class="material-icons">arrow_forward_ios</i>
                </button>
            </form>
        </div>
    </div>
</div>
